[package]
name = "observable"
version = "0.5.0"
authors = ["Gopiandcode (https://github.com/gopiandcode)"]

[dependencies]
dependent_view = {version = "1", optional = true }

[features]
views = ["dependent_view"]

[lib]
name="observable"
path="src/lib.rs"
